##START:version
#Butter version 1.2beta.175
##END:version
##START:date
#Wed Nov 1 16:48:45 2017
##END:date
##START:preamble
ROOTDIR := /home/finnerty/src/butter/trunk/test/multidir/output
OUTPUTDIR := /home/finnerty/src/butter/trunk/test/multidir/output
include $(ROOTDIR)/M_sys.mk

CPPFLAGS+=-I$(ROOTDIR)/include 
##END:preamble
##START:target Library
dirs += src/Library
##END:target Library
##START:target Executable
dirs += src/Executable
##END:target Executable
