##START:version
#Butter project version 1.2
##END:version
##START:date
#Sat Nov 27 19:46:28 2010
##END:date
##START:preamble
include makefile.sys

ROOTDIR := /tmp/multilang/output

USERHDRS := $(USERHDRS) -I$(ROOTDIR)/include

##END:preamble
##START:target Library
DIRS := $(DIRS) src/Library
##END:target Library
##START:target Executable
DIRS := $(DIRS) src/Executable
##END:target Executable
