##START:version
#Butter version 1.2beta.175
##END:version
##START:date
#Sat Oct 14 15:19:24 2017
##END:date
##START:preamble
include $(ROOTDIR)/M_sys.mk

##END:preamble
##START:target boost-test
$(eval $(call do_install,butter_exec$(sufexe),LIB))

##END:target boost-test
