##START:version
#Butter project version 1.2
##END:version
##START:date
#Sat Nov 13 18:02:25 2010
##END:date
##START:preamble
include makefile.sys

ROOTDIR := /tmp/single_test/output

##END:preamble
##START:target test
TESTSRC :=  \
	single_test.cc
TESTLDFLAGS := $(LOCALLDFLAGS)
USERFLAGS := $(LOCALFLAGS) $(SHRFLAGS)
TEST_DINC := $(filter %.d, $(TESTSRC:.cc=.d)) $(filter %.d, $(TESTSRC:.c=.d))
include $(TEST_DINC)
TEST_OBJ := $(TEST_OBJ) $(filter %.o, $(TESTSRC:.cc=.o))
USEROBJ := $(USEROBJ) $(TEST_OBJ)

test$(SUFEXE) : $(TEST_OBJ) $(TEST_DINC) 
	$(CCC) $(CCCFLAGS) -o test$(SUFEXE) $(TEST_OBJ) $(TESTLDFLAGS) $(LDFLAGS)

all :: test$(SUFEXE)
TARGETS := $(TARGETS) test$(SUFEXE)

install:: test$(SUFEXE)
	$(INSTALL) -d $(BINDIR)
	$(INSTALL) $(BINIFLAGS) test$(SUFEXE) $(BINDIR)/test$(SUFEXE)
##END:target test
