##START:version
#Butter version 1.2beta.175
##END:version
##START:date
#Sun Nov 5 17:12:49 2017
##END:date
##START:preamble
ROOTDIR := /home/finnerty/src/butter/trunk/test/single_test/output
OUTPUTDIR := /home/finnerty/src/butter/trunk/test/single_test/output
include $(ROOTDIR)/M_sys.mk

##END:preamble
##START:target test
__TESTSRC :=  \
	single_test.cc
__TEST_DINC := $(filter %$(sufdep), $(__TESTSRC:.cc=$(sufdep))) $(filter %$(sufdep), $(__TESTSRC:.c=$(sufdep)))
__TEST_OBJ+=$(filter %$(sufobj), $(__TESTSRC:.cc=$(sufobj)))
USEROBJ+=$(__TEST_OBJ)
test$(sufexe) : $(__TEST_SRC) $(__TEST_DINC)
-include $(__TEST_DINC)
$(eval $(call do_link_exe,test$(sufexe),$(__TEST_OBJ)))

all :: test$(sufexe)
TARGETS+=test$(sufexe)

$(eval $(call do_install,test$(sufexe),BIN))

##END:target test
