##START:version
#Butter version 1.2beta.175
##END:version
##START:date
#Sat Dec 9 12:43:02 2017
##END:date
##START:preamble
ROOTDIR := /home/finnerty/src/butter/trunk/test/property_test/output
OUTPUTDIR := /home/finnerty/src/butter/trunk/test/property_test/output
include $(ROOTDIR)/M_sys.mk

CPPFLAGS+=-I$(ROOTDIR)/include 
##END:preamble
##START:target Library
dirs += src/Library
##END:target Library
##START:target Executable
dirs += src/Executable
##END:target Executable
