##START:version
#Butter version 1.2beta.175
##END:version
##START:date
#Wed Nov 1 18:04:15 2017
##END:date
##START:preamble
ROOTDIR := /home/finnerty/src/butter/trunk/test/multitarget/output
OUTPUTDIR := /home/finnerty/src/butter/trunk/test/multitarget/output
include $(ROOTDIR)/M_sys.mk

##END:preamble
##START:target library
__LIBRARYSRC :=  \
	example_lib.cpp
__LIBRARY_DINC := $(filter %$(sufdep), $(__LIBRARYSRC:.cpp=$(sufdep))) $(filter %$(sufdep), $(__LIBRARYSRC:.c=$(sufdep)))
__LIBRARY_OBJ+=$(filter %$(sufobj), $(__LIBRARYSRC:.cpp=$(sufobj)))
USEROBJ+=$(__LIBRARY_OBJ)
library$(suflib) : $(__LIBRARY_SRC) $(__LIBRARY_DINC)
-include $(__LIBRARY_DINC)
$(eval $(call do_archive,library$(suflib),$(__LIBRARY_OBJ)))

all :: library$(suflib)
TARGETS+=library$(suflib)

$(eval $(call do_install,library$(suflib),LIB))

##END:target library
##START:target program
__PROGRAMSRC :=  \
	example_exe.cpp
__PROGRAM_DINC := $(filter %$(sufdep), $(__PROGRAMSRC:.cpp=$(sufdep))) $(filter %$(sufdep), $(__PROGRAMSRC:.c=$(sufdep)))
__PROGRAM_OBJ+=$(ROOTDIR)/library$(suflib)

__PROGRAM_OBJ+=$(filter %$(sufobj), $(__PROGRAMSRC:.cpp=$(sufobj)))
USEROBJ+=$(__PROGRAM_OBJ)
program$(sufexe) : $(__PROGRAM_SRC) $(__PROGRAM_DINC)
-include $(__PROGRAM_DINC)
$(eval $(call do_link_exe,program$(sufexe),$(__PROGRAM_OBJ)))

all :: program$(sufexe)
TARGETS+=program$(sufexe)

$(eval $(call do_install,program$(sufexe),BIN))

##END:target program
